enum API_ERROR_STATUS {
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    USERNAME_TAKEN = 'USERNAME_TAKEN',
    UNAUTHORIZED = 'UNAUTHORIZED',
}

export default API_ERROR_STATUS;
