openapi: 3.0.0
info:
  title: Login API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Development server
paths:
  /:
    get:
      summary: Welcome
      responses:
        '200':
          description: Welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /logout:
    post:
      security:
        - bearerAuth: []
      summary: User logout
      responses:
        '200':
          description: Successful logout
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: Successful registration
        '400':
          description: Bad request
        '500':
          description: Internal server error